### PR TITLE
Fix UI and UX

### PR DESCRIPTION
**Pull request by motahharm**
hi.

there were some UX&UX problems in this project.

i made some of them.

### CODE REVIEW

**Comment by matinturkaman** [comment]
Can you tell me what the problem was?

**Comment by motahharm** [comment]
Hi Dear @matinturkaman 
your project has some Ui&Ux problems.

This is the appearance of the project now:
prob

i made it to:
prob

and This is the appearance of the project now:
image

i made it to:
image

and i add hover effect when photo will be download

**Comment by matinturkaman** [comment]
This is not a problem. This is part of the ui

When outputting, it should not have a border radius

**Comment by motahharm** [comment]
Ok @matinturkaman 

i fix it

this is view on site:
image

and this is exported image:
Pcode (1)

**Comment by matinturkaman** [comment]
This is not part of our design

**Pull request closed without merging**
